### PR TITLE
Add dynamic prompt color

### PR DESCRIPTION
**Pull request by mzanrosso**
Added support for automatically changing the prompt color.

### CODE REVIEW

**Comment by sholderbach** [comment]
Looks good!

**Comment by mzanrosso** [comment]
I want detail better since I was in a bit of a hurry before; I created this pr so anyone can with their own interpretation of the prompt trait change the color that was previously by default to blue.

**Comment by sholderbach** [comment]
Do you want to make additional changes before merging?

**Comment by mzanrosso** [comment]
No thanks, for me it's fine

**Pull request merged**
